db_name: tomodex
deposit:
  ethereum:
    master_public_key: xpub6DxSCdWu6jKqr4isjo7bsPeDD6s3J4YVQV1JSHZg12Eagdqnf7XX4fxqyW2sLhUoFWutL7tAELU2LiGZrEXtjVbvYptvTX5Eoa4Mamdjm9u
    minimum_value_eth: 1e-05
    network_id: 8888
    rpc_server: http://localhost:8545 # The Ethereum blockchain, e.x https://mainnet.infura.io/v3/ebaf1785cc1b4f319e0ff07f26cadae8
    token_price: 1
  tomochain:
    distribution_public_key: 0x59B8515E7fF389df6926Cd52a086B0f1f46C630A
    issuer_public_key: 0x59B8515E7fF389df6926Cd52a086B0f1f46C630A
    lock_unix_timestamp: 0
    signer_private_key: 0x3411b45169aa5a8312e51357db68621031020dcf46011d7431db1bbb6d3922ce
    starting_balance: 100
    token_asset_code: WETH
error_file: config/errors.yaml
ethereum:
  decimal: 8
  exchange_address: 0xc1F424996039cc5B037dfB073bcd6e6915F0dfab
  fee_account: 0x6e6BB166F420DDd682cAEbf55dAfBaFda74f2c9c
  http_url: http://localhost:8545
  ws_url: ws://localhost:18544
jwt_signing_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
jwt_verification_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
logs:
  engine: ./engine.log
  main: ./main.log
  operator: ./operator.log
make_fee: 10000
mongo_url: 127.0.0.1
rabbitmq_url: amqp://guest:guest@localhost:5672/
server_port: 8080
simulated: false
take_fee: 10000
tick_duration:
  min:
    - 1
    - 5
    - 15
    - 30
  hour:
    - 1
    - 4
    - 12
  day:
    - 1
  week:
    - 1
  month:
    - 1
    - 3
    - 6
    - 9
  year:
    - 1

coingecko_api_url: https://api.coingecko.com/api/v3
coinmarketcap_api_url: https://pro-api.coinmarketcap.com/v1
coinmarketcap_api_key: a928d4ca-37cc-41b8-a9ea-5a65ae025aa5
supported_currencies: ETH,TOMO,BTC,USDT
env: test