# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
mongo_url: 127.0.0.1
simulated: false
server_port: 8080
db_name: tomodex
make_fee: 10000
take_fee: 10000
error_file: config/errors.yaml
rabbitmq_url: amqp://guest:guest@localhost:5672/

tick_duration:
  min:
    - 1
    - 5
    - 15
    - 30
  hour:
    - 1
    - 4
    - 12
  day:
    - 1
  week:
    - 1
  month:
    - 1
    - 3
    - 6
    - 9
  year:
    - 1

logs:
  main: ./main.log
  engine: ./engine.log
  operator: ./operator.log

ethereum:
  # Will connect to Tomochain Mainnet
  http_url: https://rpc.tomochain.com
  ws_url: wss://ws.tomochain.com
  exchange_address: 0xd68c26b99a40227C4AbE51020eDFd9BbA438B297
  fee_account: 0x6e6BB166F420DDd682cAEbf55dAfBaFda74f2c9c
  decimal: 8

# Configuration for deposit function
deposit:
#  ethereum:
#    # for demo we can deposit in the same network
#    network_id: 8888
#    master_public_key: xpub6DxSCdWu6jKqr4isjo7bsPeDD6s3J4YVQV1JSHZg12Eagdqnf7XX4fxqyW2sLhUoFWutL7tAELU2LiGZrEXtjVbvYptvTX5Eoa4Mamdjm9u
#    minimum_value_eth: 0.00001
#    token_price: 1
#    rpc_server: http://localhost:8545 # The Ethereum blockchain, e.x https://mainnet.infura.io/v3/ebaf1785cc1b4f319e0ff07f26cadae8
#    confirmed_block_number: 30
  tomochain:
    token_asset_code: WETH
    # using this private key, or secret from ENV to run smart contract
    issuer_public_key: 0x59B8515E7fF389df6926Cd52a086B0f1f46C630A
    distribution_public_key: 0x59B8515E7fF389df6926Cd52a086B0f1f46C630A
    signer_private_key: 0x3411b45169aa5a8312e51357db68621031020dcf46011d7431db1bbb6d3922ce
    starting_balance: 100.00
    lock_unix_timestamp: 0

# These are secret keys used for JWT signing and verification.
# Make sure you override these keys in production by the following environment variables:
#   RESTFUL_JWT_VERIFICATION_KEY
#   RESTFUL_JWT_SIGNING_KEY
jwt_verification_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
jwt_signing_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
# Uncomment the following line and set an appropriate JWT signing method, if needed
# The default signing method is HS256.
#jwt_signing_method: "HS256"

coingecko_api_url: https://api.coingecko.com/api/v3
coinmarketcap_api_url: https://pro-api.coinmarketcap.com/v1
coinmarketcap_api_key: a928d4ca-37cc-41b8-a9ea-5a65ae025aa5
supported_currencies: ETH,TOMO,BTC,USDT
env: prod